### PR TITLE
fix: sanitize gov v1 proposal in e2e tests for compatibility with 0.52

### LINKED ISSUE #7844: Fix e2e compatibility tests for 0.52
Currently, our e2e compatibility tests are not functional with the 0.52 upgrade.
Hopefully, this should be fully solved by https://github.com/cosmos/cosmos-sdk/pull/23347

But if there are other issues with the compatibility tests after all the version upgrades, this issue can track those as well.

Definition of done: compatibility tests work and can be run on release branches.

### PR DESCRIPTION
**Pull request by gjermundgaraba**
## Description

Closes #7844

I will run the compatibility tests with this branch before merging.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by gjermundgaraba** [comment]
I've confirmed that the compatibility tests seem to mostly work OK now. 
There are a few tests that are still failing, but it is not obvious that this is related to the 0.52 upgrade, so I pulled those out to a separate issue, so we can close this:
https://github.com/cosmos/ibc-go/issues/7864

File: e2e/testsuite/sanitize/messages.go [hunk 1]
```diff
@@ -78,6 +94,44 @@ func removeUnknownFields(tag string, msg sdk.Msg) sdk.Msg {
...
+			if err != nil {
+				panic(err)
+			}
+			msg.ClientMessage = clientMessageAny
+		}
 	}
 	return msg
 }
+
+func replaceCometBFTValidatorV1(validator *cmtproto.Validator) {
```
Comment (AdityaSripal) [inline e2e/testsuite/sanitize/messages.go:129]: nit: maybe mutate or convert instead of replace. since i expected this to be returning a new type rather than mutating in-place

**Review by AdityaSripal — APPROVED** [review]

File: e2e/testsuite/sanitize/messages.go (hunk 1 above)
Comment (gjermundgaraba) [reply e2e/testsuite/sanitize/messages.go]: Good point! Done!
